name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  go:
    uses: ./.github/workflows/go.yml
  rust:
    uses: ./.github/workflows/rust.yml
  web:
    uses: ./.github/workflows/web.yml
